export const SET_POKEMON = 'SET_POKEMON'
export const SET_DECORATION = 'SET_DECORATION'
export const SET_LOADING = 'SET_LOADING'
export const START_PLAYING = 'START_PLAYING'
export const STOP_PLAYING = 'STOP_PLAYING'
export const PLAY_SONG = 'PLAY_SONG'
export const STOP_SONG = 'STOP_SONG'
export const NEXT_SONG = 'NEXT_SONG'